### ISSUE TITLE
数据类型问题

### ISSUE THREAD

**Issue by Dindy-R** [cxyth/rs-segment.pytorch#2]
使用uint8类型的数据时会报错：
RuntimeError: gather(): Expected dtype int64 for index，
请问该怎么解决

**Comment by Dindy-R** [comment]
>

**Comment by cxyth** [comment]
需要贴上完整的报错信息，才能分析属于哪一部分的问题

**Comment by Dindy-R** [comment]
`class OwnDataset(Dataset):
    def __init__(self, lines, train, dataset_dir, transform):
        self.lines = lines
        self.train = train
        self.list = len(lines)
        self.dataset_dir = dataset_dir
        self.transform = transform
    def __len__(self):
        return self.list
    def __getitem__(self, index):
        lines = self.lines[index]
        name = lines.split()[0]
        image_paths = glob.glob(os.path.join(self.dataset_dir, "images", name + ".*"))
        image_path = image_paths[0]
        image = cv2.imread(image_path, cv2.COLOR_BGR2RGB)
        label_paths = glob.glob(os.path.join(self.dataset_dir, "labels", name + ".*"))
        label_path = label_paths[0]
        label = cv2.imread(label_path, cv2.IMREAD_GRAYSCALE)
        transformed = self.transform(image=image, label=label)
        image = transformed['image']
        label = transformed['label']
        # label = label.astype(np.int64)
        return {
            'image': image,
            'label': label
        }`
上面是我自定义的dataset，label数据是unit8的灰度图。如果把转为int64的注释掉，就会报错
![屏幕截图 2023-07-05 091528](https://github.com/cxyth/rs-segment.pytorch/assets/54894505/44db641e-b029-4797-a777-911a9d4c14ca)

**Comment by Dindy-R** [comment]
class OwnDataset(Dataset):
    def __init__(self, lines, train, dataset_dir, transform):
        self.lines = lines
        self.train = train
        self.list = len(lines)
        self.dataset_dir = dataset_dir
        self.transform = transform
        
    def __len__(self):
        return self.list

    def __getitem__(self, index):
        lines = self.lines[index]
        name = lines.split()[0]
        image_paths = glob.glob(os.path.join(self.dataset_dir, "images", name + ".*"))
        image_path = image_paths[0]
        image = cv2.imread(image_path, cv2.COLOR_BGR2RGB)
        label_paths = glob.glob(os.path.join(self.dataset_dir, "labels", name + ".*"))
        label_path = label_paths[0]
        label = cv2.imread(label_path, cv2.IMREAD_GRAYSCALE)
        transformed = self.transform(image=image, label=label)
        image = transformed['image']
        label = transformed['label']
        # label = label.astype(np.int64)
        return {
            'image': image,
            'label': label
        }
上面是我自定义的dataset类，label数据是灰度图，如果把转为int64注释掉，就会报错
![屏幕截图 2023-07-05 091528](https://github.com/cxyth/rs-segment.pytorch/assets/54894505/6c126f7d-502f-4494-aaaa-92996e1fd7b8)

**Comment by cxyth** [comment]
这是pytorch的损失函数要求输入的label是一个长整型的tensor，所以要进行 tensor.long() 类型转换，我的代码中是：

> transformed = self.transform(image=image, mask=mask)
        image = transformed['image']
        mask = transformed['mask']
        mask = mask[None, :, :]
        return {
            'image': image,
            'label': mask.long()
        }

不过看你的代码 label = label.astype(np.int64)，似乎你的transform出来仍然是np的array，而不是tensor？

**Comment by Dindy-R** [comment]
> 这是pytorch的损失函数要求输入的label是一个长整型的tensor，所以要进行 tensor.long（） 类型转换，我的代码中是：
> 
> > 已转换 = self.transform（图像=图像，掩码=掩码） 图像 = 变换[“图像”] 掩码 = 变换[“掩码”] 掩码 = 掩码[无， ：， ：] 返回 { '图像'： 图像， '标签'： 掩码.long（）
> > }
> 
> 不过看你的代码 label = label.astype（np.int64），似乎你的transform出来仍然是np的array，而不是tensor？

是的，输出数据类型仍然是nadrray，transform可以把image转成功，但label不行。

**Comment by cxyth** [comment]
你的transform是用的albumentations库吗？如果是的话应该这么写：

> transformed = self.transform(image=image, mask=label)

albumentations使用的参数名不是“label”。

**Comment by Dindy-R** [comment]
> 你的transform是用的albumentations库吗？如果是的话应该这么写：
> 
> > transformed = self.transform(image=image, mask=label)
> 
> albumentations使用的参数名不是“label”。

原来如此，已经正常了，多谢大哥
